FROM python:3.8

MAINTAINER Samuel Macko "samuel.macko.sm@gmail.com"

ENV PROJECT_DIR=/tmp/thesis_app 

WORKDIR ${PROJECT_DIR}

COPY . ${PROJECT_DIR}/

RUN pip install pipenv && \
    pipenv install --system --deploy && \
    chmod 777 -R ${PROJECT_DIR}

ENTRYPOINT [ "python", "main.py", "--compute-features", "maintained" ]