FROM registry.fedoraproject.org/f32/python3

MAINTAINER Samuel Macko "samuel.macko.sm@gmail.com"

ENV PROJECT_DIR=/tmp/thesis_app 

WORKDIR ${PROJECT_DIR}

COPY . ${PROJECT_DIR}/

USER 0
RUN chmod 777 -R ${PROJECT_DIR} && \
    pip install pipenv && \
    pipenv install --system --deploy && \

USER 1042
ENTRYPOINT [ "python", "main.py", "--compute-features", "maintained" ]
