
search_repos:
  end_condition: 'Maintained'
  end_value: 1000
  from_year: '2011'
  to_year: '2019'
  partial_upload_size: 10
  logger_file: 'search_repos.log'

  unmaintained_ids: 'unmaintained_ids.dat'
  maintained_ids: 'maintained_ids.dat'
  not_suitable_ids: 'not_suitable_ids.dat'

compute_features:
  features: 'configs/data_gathering/features.yml'
  partial_upload_size: 10
  unmaintained:
    csv_file: 'unmaintained.csv'
    ids_file: 'unmaintained_ids.dat'
    logger_file: 'compute_unmaintained.log'
  maintained:
    csv_file: 'maintained.csv'
    ids_file: 'maintained_ids.dat'
    logger_file: 'compute_maintained.log'

s3_handling:
  file_name_prefix: 'samuelmacko-thesis/'
  region: 'us-west-2'

logger:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: 'DEBUG'
